#!/usr/bin/env python2

import argparse
import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '../'))
from appscale_datastore_batch import DatastoreFactory

if __name__ == '__main__':
  parser = argparse.ArgumentParser(
    description='Checks if the data layout is valid')
  parser.add_argument('--db-type', help='The database type')
  args = parser.parse_args()

  datastore_batch = DatastoreFactory.getDatastore(args.db_type)
  assert datastore_batch.valid_data_version()
