#!/bin/bash
#
# appscale: Starts and stops appscale programs
# 
# chkconfig: 345 56 50
#
# description: Starts and stops programs for appscale   
#           
#          
# processname: appscale
PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
prog="appscale"

RETVAL=0

start() {
        echo -n $"Starting $prog: "
        echo "Starting God"
        god -c /root/appscale/AppLoadBalancer/config/global.god
        echo "0" > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts 
        #ruby /root/appscale/AppController/changeRootPwd.rb
}
stop() {
        echo -n $"Stopping $prog: "
        echo "Stopping God"
        pkill -9 god
}
restart() {
	stop
	start
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
        echo "no status to report"
	;;
  restart|reload)
	restart
	;;
  condrestart)
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|reload|condrestart}"
	exit 1
esac

exit $?
