// Code generated by protoc-gen-go from "blobstore_service.proto"
// DO NOT EDIT!

package appengine

import proto "goprotobuf.googlecode.com/hg/proto"
import "math"
import "os"


// Reference proto, math & os imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf
var _ os.Error


type BlobstoreServiceError_ErrorCode int32

const (
	BlobstoreServiceError_OK                        = 0
	BlobstoreServiceError_INTERNAL_ERROR            = 1
	BlobstoreServiceError_URL_TOO_LONG              = 2
	BlobstoreServiceError_PERMISSION_DENIED         = 3
	BlobstoreServiceError_BLOB_NOT_FOUND            = 4
	BlobstoreServiceError_DATA_INDEX_OUT_OF_RANGE   = 5
	BlobstoreServiceError_BLOB_FETCH_SIZE_TOO_LARGE = 6
)

var BlobstoreServiceError_ErrorCode_name = map[int32]string{
	0: "OK",
	1: "INTERNAL_ERROR",
	2: "URL_TOO_LONG",
	3: "PERMISSION_DENIED",
	4: "BLOB_NOT_FOUND",
	5: "DATA_INDEX_OUT_OF_RANGE",
	6: "BLOB_FETCH_SIZE_TOO_LARGE",
}
var BlobstoreServiceError_ErrorCode_value = map[string]int32{
	"OK":                        0,
	"INTERNAL_ERROR":            1,
	"URL_TOO_LONG":              2,
	"PERMISSION_DENIED":         3,
	"BLOB_NOT_FOUND":            4,
	"DATA_INDEX_OUT_OF_RANGE":   5,
	"BLOB_FETCH_SIZE_TOO_LARGE": 6,
}

func NewBlobstoreServiceError_ErrorCode(x int32) *BlobstoreServiceError_ErrorCode {
	e := BlobstoreServiceError_ErrorCode(x)
	return &e
}
func (x BlobstoreServiceError_ErrorCode) String() string {
	return proto.EnumName(BlobstoreServiceError_ErrorCode_name, int32(x))
}

type BlobstoreServiceError struct {
	XXX_unrecognized []byte
}

func (this *BlobstoreServiceError) Reset() {
	*this = BlobstoreServiceError{}
}

type CreateUploadURLRequest struct {
	SuccessPath      *string "PB(bytes,1,req,name=success_path)"
	XXX_unrecognized []byte
}

func (this *CreateUploadURLRequest) Reset() {
	*this = CreateUploadURLRequest{}
}

type CreateUploadURLResponse struct {
	Url              *string "PB(bytes,1,req,name=url)"
	XXX_unrecognized []byte
}

func (this *CreateUploadURLResponse) Reset() {
	*this = CreateUploadURLResponse{}
}

type DeleteBlobRequest struct {
	BlobKey          []string "PB(bytes,1,rep,name=blob_key)"
	XXX_unrecognized []byte
}

func (this *DeleteBlobRequest) Reset() {
	*this = DeleteBlobRequest{}
}

type FetchDataRequest struct {
	BlobKey          *string "PB(bytes,1,req,name=blob_key)"
	StartIndex       *int64  "PB(varint,2,req,name=start_index)"
	EndIndex         *int64  "PB(varint,3,req,name=end_index)"
	XXX_unrecognized []byte
}

func (this *FetchDataRequest) Reset() {
	*this = FetchDataRequest{}
}

type FetchDataResponse struct {
	Data             []byte "PB(bytes,1000,req,name=data)"
	XXX_unrecognized []byte
}

func (this *FetchDataResponse) Reset() {
	*this = FetchDataResponse{}
}

type DecodeBlobKeyRequest struct {
	BlobKey          []string "PB(bytes,1,rep,name=blob_key)"
	XXX_unrecognized []byte
}

func (this *DecodeBlobKeyRequest) Reset() {
	*this = DecodeBlobKeyRequest{}
}

type DecodeBlobKeyResponse struct {
	Decoded          []string "PB(bytes,1,rep,name=decoded)"
	XXX_unrecognized []byte
}

func (this *DecodeBlobKeyResponse) Reset() {
	*this = DecodeBlobKeyResponse{}
}

func init() {
	proto.RegisterEnum("appengine.BlobstoreServiceError_ErrorCode", BlobstoreServiceError_ErrorCode_name, BlobstoreServiceError_ErrorCode_value)
}
