# Copyright 2011 Google Inc. All rights reserved.
# Use of this source code is governed by the Apache 2.0
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc



TARG=appengine/datastore
GOFILES=\
	datastore.go\
	doc.go\
	key.go\
	load.go\
	query.go\
	save.go\
	count_dev.go\

include $(GOROOT)/src/Make.pkg
