// Code generated by protoc-gen-go.
// DO NOT EDIT!

/*
Package files is a generated protocol buffer package.

It is generated from these files:
	appengine_internal/files

It has these top-level messages:
	StringProto
	Integer32Proto
	Integer64Proto
	BoolProto
	DoubleProto
	BytesProto
	VoidProto
	FileServiceErrors
	KeyValue
	KeyValues
	FileContentType
	CreateRequest
	CreateResponse
	OpenRequest
	OpenResponse
	CloseRequest
	CloseResponse
	FileStat
	StatRequest
	StatResponse
	AppendRequest
	AppendResponse
	DeleteRequest
	DeleteResponse
	ReadRequest
	ReadResponse
	ReadKeyValueRequest
	ReadKeyValueResponse
	ShuffleEnums
	ShuffleInputSpecification
	ShuffleOutputSpecification
	ShuffleRequest
	ShuffleResponse
	GetShuffleStatusRequest
	GetShuffleStatusResponse
	GetCapabilitiesRequest
	GetCapabilitiesResponse
	FinalizeRequest
	FinalizeResponse
	GetDefaultGsBucketNameRequest
	GetDefaultGsBucketNameResponse
	ListDirRequest
	ListDirResponse
*/
package files

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type FileServiceErrors_ErrorCode int32

const (
	FileServiceErrors_OK                                 FileServiceErrors_ErrorCode = 0
	FileServiceErrors_API_TEMPORARILY_UNAVAILABLE        FileServiceErrors_ErrorCode = 1
	FileServiceErrors_REQUEST_TOO_LARGE                  FileServiceErrors_ErrorCode = 3
	FileServiceErrors_RESPONSE_TOO_LARGE                 FileServiceErrors_ErrorCode = 4
	FileServiceErrors_INVALID_FILE_NAME                  FileServiceErrors_ErrorCode = 5
	FileServiceErrors_OPERATION_NOT_SUPPORTED            FileServiceErrors_ErrorCode = 6
	FileServiceErrors_IO_ERROR                           FileServiceErrors_ErrorCode = 7
	FileServiceErrors_PERMISSION_DENIED                  FileServiceErrors_ErrorCode = 8
	FileServiceErrors_WRONG_CONTENT_TYPE                 FileServiceErrors_ErrorCode = 9
	FileServiceErrors_FILE_NOT_OPENED                    FileServiceErrors_ErrorCode = 10
	FileServiceErrors_WRONG_OPEN_MODE                    FileServiceErrors_ErrorCode = 11
	FileServiceErrors_EXCLUSIVE_LOCK_REQUIRED            FileServiceErrors_ErrorCode = 12
	FileServiceErrors_FILE_TEMPORARILY_UNAVAILABLE       FileServiceErrors_ErrorCode = 13
	FileServiceErrors_EXISTENCE_ERROR                    FileServiceErrors_ErrorCode = 100
	FileServiceErrors_FINALIZATION_ERROR                 FileServiceErrors_ErrorCode = 101
	FileServiceErrors_UNSUPPORTED_CONTENT_TYPE           FileServiceErrors_ErrorCode = 102
	FileServiceErrors_READ_ONLY                          FileServiceErrors_ErrorCode = 103
	FileServiceErrors_EXCLUSIVE_LOCK_FAILED              FileServiceErrors_ErrorCode = 104
	FileServiceErrors_EXISTENCE_ERROR_METADATA_NOT_FOUND FileServiceErrors_ErrorCode = 105
	FileServiceErrors_EXISTENCE_ERROR_METADATA_FOUND     FileServiceErrors_ErrorCode = 106
	FileServiceErrors_EXISTENCE_ERROR_SHARDING_MISMATCH  FileServiceErrors_ErrorCode = 107
	FileServiceErrors_FINALIZATION_IN_PROGRESS           FileServiceErrors_ErrorCode = 108
	FileServiceErrors_EXISTENCE_ERROR_OBJECT_NOT_FOUND   FileServiceErrors_ErrorCode = 109
	FileServiceErrors_EXISTENCE_ERROR_BUCKET_NOT_FOUND   FileServiceErrors_ErrorCode = 110
	FileServiceErrors_SEQUENCE_KEY_OUT_OF_ORDER          FileServiceErrors_ErrorCode = 300
	FileServiceErrors_OUT_OF_BOUNDS                      FileServiceErrors_ErrorCode = 500
	FileServiceErrors_GLOBS_NOT_SUPPORTED                FileServiceErrors_ErrorCode = 600
	FileServiceErrors_FILE_NAME_NOT_SPECIFIED            FileServiceErrors_ErrorCode = 701
	FileServiceErrors_FILE_NAME_SPECIFIED                FileServiceErrors_ErrorCode = 702
	FileServiceErrors_FILE_ALREADY_EXISTS                FileServiceErrors_ErrorCode = 703
	FileServiceErrors_UNSUPPORTED_FILE_SYSTEM            FileServiceErrors_ErrorCode = 704
	FileServiceErrors_INVALID_PARAMETER                  FileServiceErrors_ErrorCode = 705
	FileServiceErrors_SHUFFLER_INTERNAL_ERROR            FileServiceErrors_ErrorCode = 800
	FileServiceErrors_SHUFFLE_REQUEST_TOO_LARGE          FileServiceErrors_ErrorCode = 801
	FileServiceErrors_DUPLICATE_SHUFFLE_NAME             FileServiceErrors_ErrorCode = 802
	FileServiceErrors_SHUFFLE_NOT_AVAILABLE              FileServiceErrors_ErrorCode = 803
	FileServiceErrors_SHUFFLER_TEMPORARILY_UNAVAILABLE   FileServiceErrors_ErrorCode = 900
	FileServiceErrors_MAX_ERROR_CODE                     FileServiceErrors_ErrorCode = 9999
)

var FileServiceErrors_ErrorCode_name = map[int32]string{
	0:    "OK",
	1:    "API_TEMPORARILY_UNAVAILABLE",
	3:    "REQUEST_TOO_LARGE",
	4:    "RESPONSE_TOO_LARGE",
	5:    "INVALID_FILE_NAME",
	6:    "OPERATION_NOT_SUPPORTED",
	7:    "IO_ERROR",
	8:    "PERMISSION_DENIED",
	9:    "WRONG_CONTENT_TYPE",
	10:   "FILE_NOT_OPENED",
	11:   "WRONG_OPEN_MODE",
	12:   "EXCLUSIVE_LOCK_REQUIRED",
	13:   "FILE_TEMPORARILY_UNAVAILABLE",
	100:  "EXISTENCE_ERROR",
	101:  "FINALIZATION_ERROR",
	102:  "UNSUPPORTED_CONTENT_TYPE",
	103:  "READ_ONLY",
	104:  "EXCLUSIVE_LOCK_FAILED",
	105:  "EXISTENCE_ERROR_METADATA_NOT_FOUND",
	106:  "EXISTENCE_ERROR_METADATA_FOUND",
	107:  "EXISTENCE_ERROR_SHARDING_MISMATCH",
	108:  "FINALIZATION_IN_PROGRESS",
	109:  "EXISTENCE_ERROR_OBJECT_NOT_FOUND",
	110:  "EXISTENCE_ERROR_BUCKET_NOT_FOUND",
	300:  "SEQUENCE_KEY_OUT_OF_ORDER",
	500:  "OUT_OF_BOUNDS",
	600:  "GLOBS_NOT_SUPPORTED",
	701:  "FILE_NAME_NOT_SPECIFIED",
	702:  "FILE_NAME_SPECIFIED",
	703:  "FILE_ALREADY_EXISTS",
	704:  "UNSUPPORTED_FILE_SYSTEM",
	705:  "INVALID_PARAMETER",
	800:  "SHUFFLER_INTERNAL_ERROR",
	801:  "SHUFFLE_REQUEST_TOO_LARGE",
	802:  "DUPLICATE_SHUFFLE_NAME",
	803:  "SHUFFLE_NOT_AVAILABLE",
	900:  "SHUFFLER_TEMPORARILY_UNAVAILABLE",
	9999: "MAX_ERROR_CODE",
}
var FileServiceErrors_ErrorCode_value = map[string]int32{
	"OK": 0,
	"API_TEMPORARILY_UNAVAILABLE":        1,
	"REQUEST_TOO_LARGE":                  3,
	"RESPONSE_TOO_LARGE":                 4,
	"INVALID_FILE_NAME":                  5,
	"OPERATION_NOT_SUPPORTED":            6,
	"IO_ERROR":                           7,
	"PERMISSION_DENIED":                  8,
	"WRONG_CONTENT_TYPE":                 9,
	"FILE_NOT_OPENED":                    10,
	"WRONG_OPEN_MODE":                    11,
	"EXCLUSIVE_LOCK_REQUIRED":            12,
	"FILE_TEMPORARILY_UNAVAILABLE":       13,
	"EXISTENCE_ERROR":                    100,
	"FINALIZATION_ERROR":                 101,
	"UNSUPPORTED_CONTENT_TYPE":           102,
	"READ_ONLY":                          103,
	"EXCLUSIVE_LOCK_FAILED":              104,
	"EXISTENCE_ERROR_METADATA_NOT_FOUND": 105,
	"EXISTENCE_ERROR_METADATA_FOUND":     106,
	"EXISTENCE_ERROR_SHARDING_MISMATCH":  107,
	"FINALIZATION_IN_PROGRESS":           108,
	"EXISTENCE_ERROR_OBJECT_NOT_FOUND":   109,
	"EXISTENCE_ERROR_BUCKET_NOT_FOUND":   110,
	"SEQUENCE_KEY_OUT_OF_ORDER":          300,
	"OUT_OF_BOUNDS":                      500,
	"GLOBS_NOT_SUPPORTED":                600,
	"FILE_NAME_NOT_SPECIFIED":            701,
	"FILE_NAME_SPECIFIED":                702,
	"FILE_ALREADY_EXISTS":                703,
	"UNSUPPORTED_FILE_SYSTEM":            704,
	"INVALID_PARAMETER":                  705,
	"SHUFFLER_INTERNAL_ERROR":            800,
	"SHUFFLE_REQUEST_TOO_LARGE":          801,
	"DUPLICATE_SHUFFLE_NAME":             802,
	"SHUFFLE_NOT_AVAILABLE":              803,
	"SHUFFLER_TEMPORARILY_UNAVAILABLE":   900,
	"MAX_ERROR_CODE":                     9999,
}

func (x FileServiceErrors_ErrorCode) Enum() *FileServiceErrors_ErrorCode {
	p := new(FileServiceErrors_ErrorCode)
	*p = x
	return p
}
func (x FileServiceErrors_ErrorCode) String() string {
	return proto.EnumName(FileServiceErrors_ErrorCode_name, int32(x))
}
func (x *FileServiceErrors_ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FileServiceErrors_ErrorCode_value, data, "FileServiceErrors_ErrorCode")
	if err != nil {
		return err
	}
	*x = FileServiceErrors_ErrorCode(value)
	return nil
}

type FileContentType_ContentType int32

const (
	FileContentType_RAW          FileContentType_ContentType = 0
	FileContentType_DEPRECATED_1 FileContentType_ContentType = 2
	FileContentType_INVALID_TYPE FileContentType_ContentType = 127
)

var FileContentType_ContentType_name = map[int32]string{
	0:   "RAW",
	2:   "DEPRECATED_1",
	127: "INVALID_TYPE",
}
var FileContentType_ContentType_value = map[string]int32{
	"RAW":          0,
	"DEPRECATED_1": 2,
	"INVALID_TYPE": 127,
}

func (x FileContentType_ContentType) Enum() *FileContentType_ContentType {
	p := new(FileContentType_ContentType)
	*p = x
	return p
}
func (x FileContentType_ContentType) String() string {
	return proto.EnumName(FileContentType_ContentType_name, int32(x))
}
func (x *FileContentType_ContentType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FileContentType_ContentType_value, data, "FileContentType_ContentType")
	if err != nil {
		return err
	}
	*x = FileContentType_ContentType(value)
	return nil
}

type OpenRequest_OpenMode int32

const (
	OpenRequest_APPEND OpenRequest_OpenMode = 1
	OpenRequest_READ   OpenRequest_OpenMode = 2
)

var OpenRequest_OpenMode_name = map[int32]string{
	1: "APPEND",
	2: "READ",
}
var OpenRequest_OpenMode_value = map[string]int32{
	"APPEND": 1,
	"READ":   2,
}

func (x OpenRequest_OpenMode) Enum() *OpenRequest_OpenMode {
	p := new(OpenRequest_OpenMode)
	*p = x
	return p
}
func (x OpenRequest_OpenMode) String() string {
	return proto.EnumName(OpenRequest_OpenMode_name, int32(x))
}
func (x *OpenRequest_OpenMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OpenRequest_OpenMode_value, data, "OpenRequest_OpenMode")
	if err != nil {
		return err
	}
	*x = OpenRequest_OpenMode(value)
	return nil
}

type ShuffleEnums_InputFormat int32

const (
	ShuffleEnums_RECORDS_KEY_VALUE_PROTO_INPUT ShuffleEnums_InputFormat = 1
)

var ShuffleEnums_InputFormat_name = map[int32]string{
	1: "RECORDS_KEY_VALUE_PROTO_INPUT",
}
var ShuffleEnums_InputFormat_value = map[string]int32{
	"RECORDS_KEY_VALUE_PROTO_INPUT": 1,
}

func (x ShuffleEnums_InputFormat) Enum() *ShuffleEnums_InputFormat {
	p := new(ShuffleEnums_InputFormat)
	*p = x
	return p
}
func (x ShuffleEnums_InputFormat) String() string {
	return proto.EnumName(ShuffleEnums_InputFormat_name, int32(x))
}
func (x *ShuffleEnums_InputFormat) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ShuffleEnums_InputFormat_value, data, "ShuffleEnums_InputFormat")
	if err != nil {
		return err
	}
	*x = ShuffleEnums_InputFormat(value)
	return nil
}

type ShuffleEnums_OutputFormat int32

const (
	ShuffleEnums_RECORDS_KEY_MULTI_VALUE_PROTO_OUTPUT ShuffleEnums_OutputFormat = 1
)

var ShuffleEnums_OutputFormat_name = map[int32]string{
	1: "RECORDS_KEY_MULTI_VALUE_PROTO_OUTPUT",
}
var ShuffleEnums_OutputFormat_value = map[string]int32{
	"RECORDS_KEY_MULTI_VALUE_PROTO_OUTPUT": 1,
}

func (x ShuffleEnums_OutputFormat) Enum() *ShuffleEnums_OutputFormat {
	p := new(ShuffleEnums_OutputFormat)
	*p = x
	return p
}
func (x ShuffleEnums_OutputFormat) String() string {
	return proto.EnumName(ShuffleEnums_OutputFormat_name, int32(x))
}
func (x *ShuffleEnums_OutputFormat) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ShuffleEnums_OutputFormat_value, data, "ShuffleEnums_OutputFormat")
	if err != nil {
		return err
	}
	*x = ShuffleEnums_OutputFormat(value)
	return nil
}

type ShuffleEnums_Status int32

const (
	ShuffleEnums_UNKNOWN                      ShuffleEnums_Status = 1
	ShuffleEnums_RUNNING                      ShuffleEnums_Status = 2
	ShuffleEnums_SUCCESS                      ShuffleEnums_Status = 3
	ShuffleEnums_FAILURE                      ShuffleEnums_Status = 4
	ShuffleEnums_INVALID_INPUT                ShuffleEnums_Status = 5
	ShuffleEnums_OUTPUT_ALREADY_EXISTS        ShuffleEnums_Status = 6
	ShuffleEnums_INCORRECT_SHUFFLE_SIZE_BYTES ShuffleEnums_Status = 7
)

var ShuffleEnums_Status_name = map[int32]string{
	1: "UNKNOWN",
	2: "RUNNING",
	3: "SUCCESS",
	4: "FAILURE",
	5: "INVALID_INPUT",
	6: "OUTPUT_ALREADY_EXISTS",
	7: "INCORRECT_SHUFFLE_SIZE_BYTES",
}
var ShuffleEnums_Status_value = map[string]int32{
	"UNKNOWN":                      1,
	"RUNNING":                      2,
	"SUCCESS":                      3,
	"FAILURE":                      4,
	"INVALID_INPUT":                5,
	"OUTPUT_ALREADY_EXISTS":        6,
	"INCORRECT_SHUFFLE_SIZE_BYTES": 7,
}

func (x ShuffleEnums_Status) Enum() *ShuffleEnums_Status {
	p := new(ShuffleEnums_Status)
	*p = x
	return p
}
func (x ShuffleEnums_Status) String() string {
	return proto.EnumName(ShuffleEnums_Status_name, int32(x))
}
func (x *ShuffleEnums_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ShuffleEnums_Status_value, data, "ShuffleEnums_Status")
	if err != nil {
		return err
	}
	*x = ShuffleEnums_Status(value)
	return nil
}

type StringProto struct {
	Value            *string `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StringProto) Reset()         { *m = StringProto{} }
func (m *StringProto) String() string { return proto.CompactTextString(m) }
func (*StringProto) ProtoMessage()    {}

func (m *StringProto) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type Integer32Proto struct {
	Value            *int32 `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Integer32Proto) Reset()         { *m = Integer32Proto{} }
func (m *Integer32Proto) String() string { return proto.CompactTextString(m) }
func (*Integer32Proto) ProtoMessage()    {}

func (m *Integer32Proto) GetValue() int32 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type Integer64Proto struct {
	Value            *int64 `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Integer64Proto) Reset()         { *m = Integer64Proto{} }
func (m *Integer64Proto) String() string { return proto.CompactTextString(m) }
func (*Integer64Proto) ProtoMessage()    {}

func (m *Integer64Proto) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type BoolProto struct {
	Value            *bool  `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BoolProto) Reset()         { *m = BoolProto{} }
func (m *BoolProto) String() string { return proto.CompactTextString(m) }
func (*BoolProto) ProtoMessage()    {}

func (m *BoolProto) GetValue() bool {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return false
}

type DoubleProto struct {
	Value            *float64 `protobuf:"fixed64,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *DoubleProto) Reset()         { *m = DoubleProto{} }
func (m *DoubleProto) String() string { return proto.CompactTextString(m) }
func (*DoubleProto) ProtoMessage()    {}

func (m *DoubleProto) GetValue() float64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type BytesProto struct {
	Value            []byte `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BytesProto) Reset()         { *m = BytesProto{} }
func (m *BytesProto) String() string { return proto.CompactTextString(m) }
func (*BytesProto) ProtoMessage()    {}

func (m *BytesProto) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type VoidProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *VoidProto) Reset()         { *m = VoidProto{} }
func (m *VoidProto) String() string { return proto.CompactTextString(m) }
func (*VoidProto) ProtoMessage()    {}

type FileServiceErrors struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *FileServiceErrors) Reset()         { *m = FileServiceErrors{} }
func (m *FileServiceErrors) String() string { return proto.CompactTextString(m) }
func (*FileServiceErrors) ProtoMessage()    {}

type KeyValue struct {
	Key              []byte `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            []byte `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}

func (m *KeyValue) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KeyValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type KeyValues struct {
	Key              []byte   `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            [][]byte `protobuf:"bytes,2,rep,name=value" json:"value,omitempty"`
	Partial          *bool    `protobuf:"varint,3,opt,name=partial,def=0" json:"partial,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *KeyValues) Reset()         { *m = KeyValues{} }
func (m *KeyValues) String() string { return proto.CompactTextString(m) }
func (*KeyValues) ProtoMessage()    {}

const Default_KeyValues_Partial bool = false

func (m *KeyValues) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KeyValues) GetValue() [][]byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *KeyValues) GetPartial() bool {
	if m != nil && m.Partial != nil {
		return *m.Partial
	}
	return Default_KeyValues_Partial
}

type FileContentType struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *FileContentType) Reset()         { *m = FileContentType{} }
func (m *FileContentType) String() string { return proto.CompactTextString(m) }
func (*FileContentType) ProtoMessage()    {}

type CreateRequest struct {
	Filesystem            *string                      `protobuf:"bytes,1,req,name=filesystem" json:"filesystem,omitempty"`
	ContentType           *FileContentType_ContentType `protobuf:"varint,2,req,name=content_type,enum=files.FileContentType_ContentType" json:"content_type,omitempty"`
	Filename              *string                      `protobuf:"bytes,3,opt,name=filename" json:"filename,omitempty"`
	Parameters            []*CreateRequest_Parameter   `protobuf:"bytes,4,rep,name=parameters" json:"parameters,omitempty"`
	ExpirationTimeSeconds *int64                       `protobuf:"varint,5,opt,name=expiration_time_seconds" json:"expiration_time_seconds,omitempty"`
	XXX_unrecognized      []byte                       `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}

func (m *CreateRequest) GetFilesystem() string {
	if m != nil && m.Filesystem != nil {
		return *m.Filesystem
	}
	return ""
}

func (m *CreateRequest) GetContentType() FileContentType_ContentType {
	if m != nil && m.ContentType != nil {
		return *m.ContentType
	}
	return FileContentType_RAW
}

func (m *CreateRequest) GetFilename() string {
	if m != nil && m.Filename != nil {
		return *m.Filename
	}
	return ""
}

func (m *CreateRequest) GetParameters() []*CreateRequest_Parameter {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *CreateRequest) GetExpirationTimeSeconds() int64 {
	if m != nil && m.ExpirationTimeSeconds != nil {
		return *m.ExpirationTimeSeconds
	}
	return 0
}

type CreateRequest_Parameter struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateRequest_Parameter) Reset()         { *m = CreateRequest_Parameter{} }
func (m *CreateRequest_Parameter) String() string { return proto.CompactTextString(m) }
func (*CreateRequest_Parameter) ProtoMessage()    {}

func (m *CreateRequest_Parameter) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CreateRequest_Parameter) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type CreateResponse struct {
	Filename         *string `protobuf:"bytes,1,req,name=filename" json:"filename,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}

func (m *CreateResponse) GetFilename() string {
	if m != nil && m.Filename != nil {
		return *m.Filename
	}
	return ""
}

type OpenRequest struct {
	Filename             *string                      `protobuf:"bytes,1,req,name=filename" json:"filename,omitempty"`
	ContentType          *FileContentType_ContentType `protobuf:"varint,2,req,name=content_type,enum=files.FileContentType_ContentType" json:"content_type,omitempty"`
	OpenMode             *OpenRequest_OpenMode        `protobuf:"varint,3,req,name=open_mode,enum=files.OpenRequest_OpenMode" json:"open_mode,omitempty"`
	ExclusiveLock        *bool                        `protobuf:"varint,4,opt,name=exclusive_lock,def=0" json:"exclusive_lock,omitempty"`
	BufferedOutput       *bool                        `protobuf:"varint,5,opt,name=buffered_output,def=0" json:"buffered_output,omitempty"`
	OpenLeaseTimeSeconds *int32                       `protobuf:"varint,6,opt,name=open_lease_time_seconds,def=30" json:"open_lease_time_seconds,omitempty"`
	XXX_unrecognized     []byte                       `json:"-"`
}

func (m *OpenRequest) Reset()         { *m = OpenRequest{} }
func (m *OpenRequest) String() string { return proto.CompactTextString(m) }
func (*OpenRequest) ProtoMessage()    {}

const Default_OpenRequest_ExclusiveLock bool = false
const Default_OpenRequest_BufferedOutput bool = false
const Default_OpenRequest_OpenLeaseTimeSeconds int32 = 30

func (m *OpenRequest) GetFilename() string {
	if m != nil && m.Filename != nil {
		return *m.Filename
	}
	return ""
}

func (m *OpenRequest) GetContentType() FileContentType_ContentType {
	if m != nil && m.ContentType != nil {
		return *m.ContentType
	}
	return FileContentType_RAW
}

func (m *OpenRequest) GetOpenMode() OpenRequest_OpenMode {
	if m != nil && m.OpenMode != nil {
		return *m.OpenMode
	}
	return OpenRequest_APPEND
}

func (m *OpenRequest) GetExclusiveLock() bool {
	if m != nil && m.ExclusiveLock != nil {
		return *m.ExclusiveLock
	}
	return Default_OpenRequest_ExclusiveLock
}

func (m *OpenRequest) GetBufferedOutput() bool {
	if m != nil && m.BufferedOutput != nil {
		return *m.BufferedOutput
	}
	return Default_OpenRequest_BufferedOutput
}

func (m *OpenRequest) GetOpenLeaseTimeSeconds() int32 {
	if m != nil && m.OpenLeaseTimeSeconds != nil {
		return *m.OpenLeaseTimeSeconds
	}
	return Default_OpenRequest_OpenLeaseTimeSeconds
}

type OpenResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *OpenResponse) Reset()         { *m = OpenResponse{} }
func (m *OpenResponse) String() string { return proto.CompactTextString(m) }
func (*OpenResponse) ProtoMessage()    {}

type CloseRequest struct {
	Filename         *string `protobuf:"bytes,1,req,name=filename" json:"filename,omitempty"`
	Finalize         *bool   `protobuf:"varint,2,opt,name=finalize,def=0" json:"finalize,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CloseRequest) Reset()         { *m = CloseRequest{} }
func (m *CloseRequest) String() string { return proto.CompactTextString(m) }
func (*CloseRequest) ProtoMessage()    {}

const Default_CloseRequest_Finalize bool = false

func (m *CloseRequest) GetFilename() string {
	if m != nil && m.Filename != nil {
		return *m.Filename
	}
	return ""
}

func (m *CloseRequest) GetFinalize() bool {
	if m != nil && m.Finalize != nil {
		return *m.Finalize
	}
	return Default_CloseRequest_Finalize
}

type CloseResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CloseResponse) Reset()         { *m = CloseResponse{} }
func (m *CloseResponse) String() string { return proto.CompactTextString(m) }
func (*CloseResponse) ProtoMessage()    {}

type FileStat struct {
	Filename         *string                      `protobuf:"bytes,1,req,name=filename" json:"filename,omitempty"`
	ContentType      *FileContentType_ContentType `protobuf:"varint,2,req,name=content_type,enum=files.FileContentType_ContentType" json:"content_type,omitempty"`
	Finalized        *bool                        `protobuf:"varint,3,req,name=finalized" json:"finalized,omitempty"`
	Length           *int64                       `protobuf:"varint,4,opt,name=length" json:"length,omitempty"`
	Ctime            *int64                       `protobuf:"varint,5,opt,name=ctime" json:"ctime,omitempty"`
	Mtime            *int64                       `protobuf:"varint,6,opt,name=mtime" json:"mtime,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *FileStat) Reset()         { *m = FileStat{} }
func (m *FileStat) String() string { return proto.CompactTextString(m) }
func (*FileStat) ProtoMessage()    {}

func (m *FileStat) GetFilename() string {
	if m != nil && m.Filename != nil {
		return *m.Filename
	}
	return ""
}

func (m *FileStat) GetContentType() FileContentType_ContentType {
	if m != nil && m.ContentType != nil {
		return *m.ContentType
	}
	return FileContentType_RAW
}

func (m *FileStat) GetFinalized() bool {
	if m != nil && m.Finalized != nil {
		return *m.Finalized
	}
	return false
}

func (m *FileStat) GetLength() int64 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *FileStat) GetCtime() int64 {
	if m != nil && m.Ctime != nil {
		return *m.Ctime
	}
	return 0
}

func (m *FileStat) GetMtime() int64 {
	if m != nil && m.Mtime != nil {
		return *m.Mtime
	}
	return 0
}

type StatRequest struct {
	Filename         *string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	FileGlob         *string `protobuf:"bytes,2,opt,name=file_glob" json:"file_glob,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StatRequest) Reset()         { *m = StatRequest{} }
func (m *StatRequest) String() string { return proto.CompactTextString(m) }
func (*StatRequest) ProtoMessage()    {}

func (m *StatRequest) GetFilename() string {
	if m != nil && m.Filename != nil {
		return *m.Filename
	}
	return ""
}

func (m *StatRequest) GetFileGlob() string {
	if m != nil && m.FileGlob != nil {
		return *m.FileGlob
	}
	return ""
}

type StatResponse struct {
	Stat             []*FileStat `protobuf:"bytes,1,rep,name=stat" json:"stat,omitempty"`
	MoreFilesFound   *bool       `protobuf:"varint,2,req,name=more_files_found,def=0" json:"more_files_found,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *StatResponse) Reset()         { *m = StatResponse{} }
func (m *StatResponse) String() string { return proto.CompactTextString(m) }
func (*StatResponse) ProtoMessage()    {}

const Default_StatResponse_MoreFilesFound bool = false

func (m *StatResponse) GetStat() []*FileStat {
	if m != nil {
		return m.Stat
	}
	return nil
}

func (m *StatResponse) GetMoreFilesFound() bool {
	if m != nil && m.MoreFilesFound != nil {
		return *m.MoreFilesFound
	}
	return Default_StatResponse_MoreFilesFound
}

type AppendRequest struct {
	Filename         *string `protobuf:"bytes,1,req,name=filename" json:"filename,omitempty"`
	Data             []byte  `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	SequenceKey      *string `protobuf:"bytes,3,opt,name=sequence_key" json:"sequence_key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AppendRequest) Reset()         { *m = AppendRequest{} }
func (m *AppendRequest) String() string { return proto.CompactTextString(m) }
func (*AppendRequest) ProtoMessage()    {}

func (m *AppendRequest) GetFilename() string {
	if m != nil && m.Filename != nil {
		return *m.Filename
	}
	return ""
}

func (m *AppendRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AppendRequest) GetSequenceKey() string {
	if m != nil && m.SequenceKey != nil {
		return *m.SequenceKey
	}
	return ""
}

type AppendResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *AppendResponse) Reset()         { *m = AppendResponse{} }
func (m *AppendResponse) String() string { return proto.CompactTextString(m) }
func (*AppendResponse) ProtoMessage()    {}

type DeleteRequest struct {
	Filename         *string `protobuf:"bytes,1,req,name=filename" json:"filename,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}

func (m *DeleteRequest) GetFilename() string {
	if m != nil && m.Filename != nil {
		return *m.Filename
	}
	return ""
}

type DeleteResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}

type ReadRequest struct {
	Filename         *string `protobuf:"bytes,1,req,name=filename" json:"filename,omitempty"`
	Pos              *int64  `protobuf:"varint,2,req,name=pos" json:"pos,omitempty"`
	MaxBytes         *int64  `protobuf:"varint,3,req,name=max_bytes" json:"max_bytes,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}

func (m *ReadRequest) GetFilename() string {
	if m != nil && m.Filename != nil {
		return *m.Filename
	}
	return ""
}

func (m *ReadRequest) GetPos() int64 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func (m *ReadRequest) GetMaxBytes() int64 {
	if m != nil && m.MaxBytes != nil {
		return *m.MaxBytes
	}
	return 0
}

type ReadResponse struct {
	Data             []byte `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}

func (m *ReadResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ReadKeyValueRequest struct {
	Filename         *string `protobuf:"bytes,1,req,name=filename" json:"filename,omitempty"`
	StartKey         []byte  `protobuf:"bytes,2,req,name=start_key" json:"start_key,omitempty"`
	MaxBytes         *int64  `protobuf:"varint,3,req,name=max_bytes" json:"max_bytes,omitempty"`
	ValuePos         *int64  `protobuf:"varint,4,opt,name=value_pos" json:"value_pos,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReadKeyValueRequest) Reset()         { *m = ReadKeyValueRequest{} }
func (m *ReadKeyValueRequest) String() string { return proto.CompactTextString(m) }
func (*ReadKeyValueRequest) ProtoMessage()    {}

func (m *ReadKeyValueRequest) GetFilename() string {
	if m != nil && m.Filename != nil {
		return *m.Filename
	}
	return ""
}

func (m *ReadKeyValueRequest) GetStartKey() []byte {
	if m != nil {
		return m.StartKey
	}
	return nil
}

func (m *ReadKeyValueRequest) GetMaxBytes() int64 {
	if m != nil && m.MaxBytes != nil {
		return *m.MaxBytes
	}
	return 0
}

func (m *ReadKeyValueRequest) GetValuePos() int64 {
	if m != nil && m.ValuePos != nil {
		return *m.ValuePos
	}
	return 0
}

type ReadKeyValueResponse struct {
	Data             []*ReadKeyValueResponse_KeyValue `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
	NextKey          []byte                           `protobuf:"bytes,2,opt,name=next_key" json:"next_key,omitempty"`
	TruncatedValue   *bool                            `protobuf:"varint,3,opt,name=truncated_value" json:"truncated_value,omitempty"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (m *ReadKeyValueResponse) Reset()         { *m = ReadKeyValueResponse{} }
func (m *ReadKeyValueResponse) String() string { return proto.CompactTextString(m) }
func (*ReadKeyValueResponse) ProtoMessage()    {}

func (m *ReadKeyValueResponse) GetData() []*ReadKeyValueResponse_KeyValue {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ReadKeyValueResponse) GetNextKey() []byte {
	if m != nil {
		return m.NextKey
	}
	return nil
}

func (m *ReadKeyValueResponse) GetTruncatedValue() bool {
	if m != nil && m.TruncatedValue != nil {
		return *m.TruncatedValue
	}
	return false
}

type ReadKeyValueResponse_KeyValue struct {
	Key              []byte `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            []byte `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ReadKeyValueResponse_KeyValue) Reset()         { *m = ReadKeyValueResponse_KeyValue{} }
func (m *ReadKeyValueResponse_KeyValue) String() string { return proto.CompactTextString(m) }
func (*ReadKeyValueResponse_KeyValue) ProtoMessage()    {}

func (m *ReadKeyValueResponse_KeyValue) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ReadKeyValueResponse_KeyValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type ShuffleEnums struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ShuffleEnums) Reset()         { *m = ShuffleEnums{} }
func (m *ShuffleEnums) String() string { return proto.CompactTextString(m) }
func (*ShuffleEnums) ProtoMessage()    {}

type ShuffleInputSpecification struct {
	Format           *ShuffleEnums_InputFormat `protobuf:"varint,1,opt,name=format,enum=files.ShuffleEnums_InputFormat,def=1" json:"format,omitempty"`
	Path             *string                   `protobuf:"bytes,2,req,name=path" json:"path,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *ShuffleInputSpecification) Reset()         { *m = ShuffleInputSpecification{} }
func (m *ShuffleInputSpecification) String() string { return proto.CompactTextString(m) }
func (*ShuffleInputSpecification) ProtoMessage()    {}

const Default_ShuffleInputSpecification_Format ShuffleEnums_InputFormat = ShuffleEnums_RECORDS_KEY_VALUE_PROTO_INPUT

func (m *ShuffleInputSpecification) GetFormat() ShuffleEnums_InputFormat {
	if m != nil && m.Format != nil {
		return *m.Format
	}
	return Default_ShuffleInputSpecification_Format
}

func (m *ShuffleInputSpecification) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

type ShuffleOutputSpecification struct {
	Format           *ShuffleEnums_OutputFormat `protobuf:"varint,1,opt,name=format,enum=files.ShuffleEnums_OutputFormat,def=1" json:"format,omitempty"`
	Path             []string                   `protobuf:"bytes,2,rep,name=path" json:"path,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *ShuffleOutputSpecification) Reset()         { *m = ShuffleOutputSpecification{} }
func (m *ShuffleOutputSpecification) String() string { return proto.CompactTextString(m) }
func (*ShuffleOutputSpecification) ProtoMessage()    {}

const Default_ShuffleOutputSpecification_Format ShuffleEnums_OutputFormat = ShuffleEnums_RECORDS_KEY_MULTI_VALUE_PROTO_OUTPUT

func (m *ShuffleOutputSpecification) GetFormat() ShuffleEnums_OutputFormat {
	if m != nil && m.Format != nil {
		return *m.Format
	}
	return Default_ShuffleOutputSpecification_Format
}

func (m *ShuffleOutputSpecification) GetPath() []string {
	if m != nil {
		return m.Path
	}
	return nil
}

type ShuffleRequest struct {
	ShuffleName      *string                      `protobuf:"bytes,1,req,name=shuffle_name" json:"shuffle_name,omitempty"`
	Input            []*ShuffleInputSpecification `protobuf:"bytes,2,rep,name=input" json:"input,omitempty"`
	Output           *ShuffleOutputSpecification  `protobuf:"bytes,3,req,name=output" json:"output,omitempty"`
	ShuffleSizeBytes *int64                       `protobuf:"varint,4,req,name=shuffle_size_bytes" json:"shuffle_size_bytes,omitempty"`
	Callback         *ShuffleRequest_Callback     `protobuf:"bytes,5,req,name=callback" json:"callback,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *ShuffleRequest) Reset()         { *m = ShuffleRequest{} }
func (m *ShuffleRequest) String() string { return proto.CompactTextString(m) }
func (*ShuffleRequest) ProtoMessage()    {}

func (m *ShuffleRequest) GetShuffleName() string {
	if m != nil && m.ShuffleName != nil {
		return *m.ShuffleName
	}
	return ""
}

func (m *ShuffleRequest) GetInput() []*ShuffleInputSpecification {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *ShuffleRequest) GetOutput() *ShuffleOutputSpecification {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *ShuffleRequest) GetShuffleSizeBytes() int64 {
	if m != nil && m.ShuffleSizeBytes != nil {
		return *m.ShuffleSizeBytes
	}
	return 0
}

func (m *ShuffleRequest) GetCallback() *ShuffleRequest_Callback {
	if m != nil {
		return m.Callback
	}
	return nil
}

type ShuffleRequest_Callback struct {
	Url              *string `protobuf:"bytes,1,req,name=url" json:"url,omitempty"`
	AppVersionId     *string `protobuf:"bytes,2,opt,name=app_version_id" json:"app_version_id,omitempty"`
	Method           *string `protobuf:"bytes,3,opt,name=method,def=POST" json:"method,omitempty"`
	Queue            *string `protobuf:"bytes,4,opt,name=queue,def=default" json:"queue,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ShuffleRequest_Callback) Reset()         { *m = ShuffleRequest_Callback{} }
func (m *ShuffleRequest_Callback) String() string { return proto.CompactTextString(m) }
func (*ShuffleRequest_Callback) ProtoMessage()    {}

const Default_ShuffleRequest_Callback_Method string = "POST"
const Default_ShuffleRequest_Callback_Queue string = "default"

func (m *ShuffleRequest_Callback) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *ShuffleRequest_Callback) GetAppVersionId() string {
	if m != nil && m.AppVersionId != nil {
		return *m.AppVersionId
	}
	return ""
}

func (m *ShuffleRequest_Callback) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return Default_ShuffleRequest_Callback_Method
}

func (m *ShuffleRequest_Callback) GetQueue() string {
	if m != nil && m.Queue != nil {
		return *m.Queue
	}
	return Default_ShuffleRequest_Callback_Queue
}

type ShuffleResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ShuffleResponse) Reset()         { *m = ShuffleResponse{} }
func (m *ShuffleResponse) String() string { return proto.CompactTextString(m) }
func (*ShuffleResponse) ProtoMessage()    {}

type GetShuffleStatusRequest struct {
	ShuffleName      *string `protobuf:"bytes,1,req,name=shuffle_name" json:"shuffle_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetShuffleStatusRequest) Reset()         { *m = GetShuffleStatusRequest{} }
func (m *GetShuffleStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetShuffleStatusRequest) ProtoMessage()    {}

func (m *GetShuffleStatusRequest) GetShuffleName() string {
	if m != nil && m.ShuffleName != nil {
		return *m.ShuffleName
	}
	return ""
}

type GetShuffleStatusResponse struct {
	Status           *ShuffleEnums_Status `protobuf:"varint,1,req,name=status,enum=files.ShuffleEnums_Status" json:"status,omitempty"`
	Description      *string              `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *GetShuffleStatusResponse) Reset()         { *m = GetShuffleStatusResponse{} }
func (m *GetShuffleStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetShuffleStatusResponse) ProtoMessage()    {}

func (m *GetShuffleStatusResponse) GetStatus() ShuffleEnums_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ShuffleEnums_UNKNOWN
}

func (m *GetShuffleStatusResponse) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

type GetCapabilitiesRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetCapabilitiesRequest) Reset()         { *m = GetCapabilitiesRequest{} }
func (m *GetCapabilitiesRequest) String() string { return proto.CompactTextString(m) }
func (*GetCapabilitiesRequest) ProtoMessage()    {}

type GetCapabilitiesResponse struct {
	Filesystem       []string `protobuf:"bytes,1,rep,name=filesystem" json:"filesystem,omitempty"`
	ShuffleAvailable *bool    `protobuf:"varint,2,req,name=shuffle_available" json:"shuffle_available,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GetCapabilitiesResponse) Reset()         { *m = GetCapabilitiesResponse{} }
func (m *GetCapabilitiesResponse) String() string { return proto.CompactTextString(m) }
func (*GetCapabilitiesResponse) ProtoMessage()    {}

func (m *GetCapabilitiesResponse) GetFilesystem() []string {
	if m != nil {
		return m.Filesystem
	}
	return nil
}

func (m *GetCapabilitiesResponse) GetShuffleAvailable() bool {
	if m != nil && m.ShuffleAvailable != nil {
		return *m.ShuffleAvailable
	}
	return false
}

type FinalizeRequest struct {
	Filename         *string `protobuf:"bytes,1,req,name=filename" json:"filename,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FinalizeRequest) Reset()         { *m = FinalizeRequest{} }
func (m *FinalizeRequest) String() string { return proto.CompactTextString(m) }
func (*FinalizeRequest) ProtoMessage()    {}

func (m *FinalizeRequest) GetFilename() string {
	if m != nil && m.Filename != nil {
		return *m.Filename
	}
	return ""
}

type FinalizeResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *FinalizeResponse) Reset()         { *m = FinalizeResponse{} }
func (m *FinalizeResponse) String() string { return proto.CompactTextString(m) }
func (*FinalizeResponse) ProtoMessage()    {}

type GetDefaultGsBucketNameRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetDefaultGsBucketNameRequest) Reset()         { *m = GetDefaultGsBucketNameRequest{} }
func (m *GetDefaultGsBucketNameRequest) String() string { return proto.CompactTextString(m) }
func (*GetDefaultGsBucketNameRequest) ProtoMessage()    {}

type GetDefaultGsBucketNameResponse struct {
	DefaultGsBucketName *string `protobuf:"bytes,1,opt,name=default_gs_bucket_name" json:"default_gs_bucket_name,omitempty"`
	XXX_unrecognized    []byte  `json:"-"`
}

func (m *GetDefaultGsBucketNameResponse) Reset()         { *m = GetDefaultGsBucketNameResponse{} }
func (m *GetDefaultGsBucketNameResponse) String() string { return proto.CompactTextString(m) }
func (*GetDefaultGsBucketNameResponse) ProtoMessage()    {}

func (m *GetDefaultGsBucketNameResponse) GetDefaultGsBucketName() string {
	if m != nil && m.DefaultGsBucketName != nil {
		return *m.DefaultGsBucketName
	}
	return ""
}

type ListDirRequest struct {
	Path             *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Marker           *string `protobuf:"bytes,2,opt,name=marker" json:"marker,omitempty"`
	MaxKeys          *int64  `protobuf:"varint,3,opt,name=max_keys" json:"max_keys,omitempty"`
	Prefix           *string `protobuf:"bytes,4,opt,name=prefix" json:"prefix,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ListDirRequest) Reset()         { *m = ListDirRequest{} }
func (m *ListDirRequest) String() string { return proto.CompactTextString(m) }
func (*ListDirRequest) ProtoMessage()    {}

func (m *ListDirRequest) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *ListDirRequest) GetMarker() string {
	if m != nil && m.Marker != nil {
		return *m.Marker
	}
	return ""
}

func (m *ListDirRequest) GetMaxKeys() int64 {
	if m != nil && m.MaxKeys != nil {
		return *m.MaxKeys
	}
	return 0
}

func (m *ListDirRequest) GetPrefix() string {
	if m != nil && m.Prefix != nil {
		return *m.Prefix
	}
	return ""
}

type ListDirResponse struct {
	Filenames        []string `protobuf:"bytes,1,rep,name=filenames" json:"filenames,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ListDirResponse) Reset()         { *m = ListDirResponse{} }
func (m *ListDirResponse) String() string { return proto.CompactTextString(m) }
func (*ListDirResponse) ProtoMessage()    {}

func (m *ListDirResponse) GetFilenames() []string {
	if m != nil {
		return m.Filenames
	}
	return nil
}

func init() {
	proto.RegisterEnum("files.FileServiceErrors_ErrorCode", FileServiceErrors_ErrorCode_name, FileServiceErrors_ErrorCode_value)
	proto.RegisterEnum("files.FileContentType_ContentType", FileContentType_ContentType_name, FileContentType_ContentType_value)
	proto.RegisterEnum("files.OpenRequest_OpenMode", OpenRequest_OpenMode_name, OpenRequest_OpenMode_value)
	proto.RegisterEnum("files.ShuffleEnums_InputFormat", ShuffleEnums_InputFormat_name, ShuffleEnums_InputFormat_value)
	proto.RegisterEnum("files.ShuffleEnums_OutputFormat", ShuffleEnums_OutputFormat_name, ShuffleEnums_OutputFormat_value)
	proto.RegisterEnum("files.ShuffleEnums_Status", ShuffleEnums_Status_name, ShuffleEnums_Status_value)
}
