# Description: V 0.7.2 of pretty table https://code.google.com/p/prettytable/
package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # BSD

exports_files(["LICENSE"])

py_library(
    name = "prettytable",
    srcs = ["__init__.py"],
)
