// Code generated by protoc-gen-go from "user_service.proto"
// DO NOT EDIT!

package appengine

import proto "goprotobuf.googlecode.com/hg/proto"
import "math"
import "os"


// Reference proto, math & os imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf
var _ os.Error


type UserServiceError_ErrorCode int32

const (
	UserServiceError_OK                    = 0
	UserServiceError_REDIRECT_URL_TOO_LONG = 1
	UserServiceError_NOT_ALLOWED           = 2
	UserServiceError_OAUTH_INVALID_TOKEN   = 3
	UserServiceError_OAUTH_INVALID_REQUEST = 4
	UserServiceError_OAUTH_ERROR           = 5
)

var UserServiceError_ErrorCode_name = map[int32]string{
	0: "OK",
	1: "REDIRECT_URL_TOO_LONG",
	2: "NOT_ALLOWED",
	3: "OAUTH_INVALID_TOKEN",
	4: "OAUTH_INVALID_REQUEST",
	5: "OAUTH_ERROR",
}
var UserServiceError_ErrorCode_value = map[string]int32{
	"OK": 0,
	"REDIRECT_URL_TOO_LONG": 1,
	"NOT_ALLOWED":           2,
	"OAUTH_INVALID_TOKEN":   3,
	"OAUTH_INVALID_REQUEST": 4,
	"OAUTH_ERROR":           5,
}

func NewUserServiceError_ErrorCode(x int32) *UserServiceError_ErrorCode {
	e := UserServiceError_ErrorCode(x)
	return &e
}
func (x UserServiceError_ErrorCode) String() string {
	return proto.EnumName(UserServiceError_ErrorCode_name, int32(x))
}

type UserServiceError struct {
	XXX_unrecognized []byte
}

func (this *UserServiceError) Reset() {
	*this = UserServiceError{}
}

type CreateLoginURLRequest struct {
	DestinationUrl    *string "PB(bytes,1,req,name=destination_url)"
	AuthDomain        *string "PB(bytes,2,opt,name=auth_domain)"
	FederatedIdentity *string "PB(bytes,3,opt,name=federated_identity)"
	XXX_unrecognized  []byte
}

func (this *CreateLoginURLRequest) Reset() {
	*this = CreateLoginURLRequest{}
}

type CreateLoginURLResponse struct {
	LoginUrl         *string "PB(bytes,1,req,name=login_url)"
	XXX_unrecognized []byte
}

func (this *CreateLoginURLResponse) Reset() {
	*this = CreateLoginURLResponse{}
}

type CreateLogoutURLRequest struct {
	DestinationUrl   *string "PB(bytes,1,req,name=destination_url)"
	AuthDomain       *string "PB(bytes,2,opt,name=auth_domain)"
	XXX_unrecognized []byte
}

func (this *CreateLogoutURLRequest) Reset() {
	*this = CreateLogoutURLRequest{}
}

type CreateLogoutURLResponse struct {
	LogoutUrl        *string "PB(bytes,1,req,name=logout_url)"
	XXX_unrecognized []byte
}

func (this *CreateLogoutURLResponse) Reset() {
	*this = CreateLogoutURLResponse{}
}

type GetOAuthUserRequest struct {
	Scope            *string "PB(bytes,1,opt,name=scope)"
	XXX_unrecognized []byte
}

func (this *GetOAuthUserRequest) Reset() {
	*this = GetOAuthUserRequest{}
}

type GetOAuthUserResponse struct {
	Email            *string "PB(bytes,1,req,name=email)"
	UserId           *string "PB(bytes,2,req,name=user_id)"
	AuthDomain       *string "PB(bytes,3,req,name=auth_domain)"
	UserOrganization *string "PB(bytes,4,opt,name=user_organization)"
	IsAdmin          *bool   "PB(varint,5,opt,name=is_admin,def=0)"
	XXX_unrecognized []byte
}

func (this *GetOAuthUserResponse) Reset() {
	*this = GetOAuthUserResponse{}
}

const Default_GetOAuthUserResponse_IsAdmin bool = false

type CheckOAuthSignatureRequest struct {
	XXX_unrecognized []byte
}

func (this *CheckOAuthSignatureRequest) Reset() {
	*this = CheckOAuthSignatureRequest{}
}

type CheckOAuthSignatureResponse struct {
	OauthConsumerKey *string "PB(bytes,1,req,name=oauth_consumer_key)"
	XXX_unrecognized []byte
}

func (this *CheckOAuthSignatureResponse) Reset() {
	*this = CheckOAuthSignatureResponse{}
}

type CreateFederatedLoginRequest struct {
	ClaimedId        *string "PB(bytes,1,req,name=claimed_id)"
	ContinueUrl      *string "PB(bytes,2,req,name=continue_url)"
	Authority        *string "PB(bytes,3,opt,name=authority)"
	XXX_unrecognized []byte
}

func (this *CreateFederatedLoginRequest) Reset() {
	*this = CreateFederatedLoginRequest{}
}

type CreateFederatedLoginResponse struct {
	RedirectedUrl    *string "PB(bytes,1,req,name=redirected_url)"
	XXX_unrecognized []byte
}

func (this *CreateFederatedLoginResponse) Reset() {
	*this = CreateFederatedLoginResponse{}
}

type CreateFederatedLogoutRequest struct {
	DestinationUrl   *string "PB(bytes,1,req,name=destination_url)"
	XXX_unrecognized []byte
}

func (this *CreateFederatedLogoutRequest) Reset() {
	*this = CreateFederatedLogoutRequest{}
}

type CreateFederatedLogoutResponse struct {
	LogoutUrl        *string "PB(bytes,1,req,name=logout_url)"
	XXX_unrecognized []byte
}

func (this *CreateFederatedLogoutResponse) Reset() {
	*this = CreateFederatedLogoutResponse{}
}

func init() {
	proto.RegisterEnum("appengine.UserServiceError_ErrorCode", UserServiceError_ErrorCode_name, UserServiceError_ErrorCode_value)
}
