// Code generated by protoc-gen-go from "urlfetch_service.proto"
// DO NOT EDIT!

package appengine

import proto "goprotobuf.googlecode.com/hg/proto"
import "math"
import "os"


// Reference proto, math & os imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf
var _ os.Error


type URLFetchServiceError_ErrorCode int32

const (
	URLFetchServiceError_OK                    = 0
	URLFetchServiceError_INVALID_URL           = 1
	URLFetchServiceError_FETCH_ERROR           = 2
	URLFetchServiceError_UNSPECIFIED_ERROR     = 3
	URLFetchServiceError_RESPONSE_TOO_LARGE    = 4
	URLFetchServiceError_DEADLINE_EXCEEDED     = 5
	URLFetchServiceError_SSL_CERTIFICATE_ERROR = 6
)

var URLFetchServiceError_ErrorCode_name = map[int32]string{
	0: "OK",
	1: "INVALID_URL",
	2: "FETCH_ERROR",
	3: "UNSPECIFIED_ERROR",
	4: "RESPONSE_TOO_LARGE",
	5: "DEADLINE_EXCEEDED",
	6: "SSL_CERTIFICATE_ERROR",
}
var URLFetchServiceError_ErrorCode_value = map[string]int32{
	"OK":                    0,
	"INVALID_URL":           1,
	"FETCH_ERROR":           2,
	"UNSPECIFIED_ERROR":     3,
	"RESPONSE_TOO_LARGE":    4,
	"DEADLINE_EXCEEDED":     5,
	"SSL_CERTIFICATE_ERROR": 6,
}

func NewURLFetchServiceError_ErrorCode(x int32) *URLFetchServiceError_ErrorCode {
	e := URLFetchServiceError_ErrorCode(x)
	return &e
}
func (x URLFetchServiceError_ErrorCode) String() string {
	return proto.EnumName(URLFetchServiceError_ErrorCode_name, int32(x))
}

type URLFetchRequest_RequestMethod int32

const (
	URLFetchRequest_GET    = 1
	URLFetchRequest_POST   = 2
	URLFetchRequest_HEAD   = 3
	URLFetchRequest_PUT    = 4
	URLFetchRequest_DELETE = 5
)

var URLFetchRequest_RequestMethod_name = map[int32]string{
	1: "GET",
	2: "POST",
	3: "HEAD",
	4: "PUT",
	5: "DELETE",
}
var URLFetchRequest_RequestMethod_value = map[string]int32{
	"GET":    1,
	"POST":   2,
	"HEAD":   3,
	"PUT":    4,
	"DELETE": 5,
}

func NewURLFetchRequest_RequestMethod(x int32) *URLFetchRequest_RequestMethod {
	e := URLFetchRequest_RequestMethod(x)
	return &e
}
func (x URLFetchRequest_RequestMethod) String() string {
	return proto.EnumName(URLFetchRequest_RequestMethod_name, int32(x))
}

type URLFetchServiceError struct {
	XXX_unrecognized []byte
}

func (this *URLFetchServiceError) Reset() {
	*this = URLFetchServiceError{}
}

type URLFetchRequest struct {
	Method                        *URLFetchRequest_RequestMethod "PB(varint,1,req,enum=appengine.URLFetchRequest_RequestMethod)"
	Url                           *string                        "PB(bytes,2,req)"
	Header                        []*URLFetchRequest_Header      "PB(group,3,rep,name=Header)"
	Payload                       []byte                         "PB(bytes,6,opt)"
	FollowRedirects               *bool                          "PB(varint,7,opt,def=1)"
	Deadline                      *float64                       "PB(fixed64,8,opt)"
	MustValidateServerCertificate *bool                          "PB(varint,9,opt,def=1)"
	XXX_unrecognized              []byte
}

func (this *URLFetchRequest) Reset() {
	*this = URLFetchRequest{}
}

const Default_URLFetchRequest_FollowRedirects bool = true
const Default_URLFetchRequest_MustValidateServerCertificate bool = true

type URLFetchRequest_Header struct {
	Key              *string "PB(bytes,4,req)"
	Value            *string "PB(bytes,5,req)"
	XXX_unrecognized []byte
}

func (this *URLFetchRequest_Header) Reset() {
	*this = URLFetchRequest_Header{}
}

type URLFetchResponse struct {
	Content               []byte                     "PB(bytes,1,opt)"
	StatusCode            *int32                     "PB(varint,2,req)"
	Header                []*URLFetchResponse_Header "PB(group,3,rep,name=Header)"
	ContentWasTruncated   *bool                      "PB(varint,6,opt,def=0)"
	ExternalBytesSent     *int64                     "PB(varint,7,opt)"
	ExternalBytesReceived *int64                     "PB(varint,8,opt)"
	FinalUrl              *string                    "PB(bytes,9,opt)"
	ApiCpuMilliseconds    *int64                     "PB(varint,10,opt,def=0)"
	ApiBytesSent          *int64                     "PB(varint,11,opt,def=0)"
	ApiBytesReceived      *int64                     "PB(varint,12,opt,def=0)"
	XXX_unrecognized      []byte
}

func (this *URLFetchResponse) Reset() {
	*this = URLFetchResponse{}
}

const Default_URLFetchResponse_ContentWasTruncated bool = false
const Default_URLFetchResponse_ApiCpuMilliseconds int64 = 0
const Default_URLFetchResponse_ApiBytesSent int64 = 0
const Default_URLFetchResponse_ApiBytesReceived int64 = 0

type URLFetchResponse_Header struct {
	Key              *string "PB(bytes,4,req)"
	Value            *string "PB(bytes,5,req)"
	XXX_unrecognized []byte
}

func (this *URLFetchResponse_Header) Reset() {
	*this = URLFetchResponse_Header{}
}

func init() {
	proto.RegisterEnum("appengine.URLFetchServiceError_ErrorCode", URLFetchServiceError_ErrorCode_name, URLFetchServiceError_ErrorCode_value)
	proto.RegisterEnum("appengine.URLFetchRequest_RequestMethod", URLFetchRequest_RequestMethod_name, URLFetchRequest_RequestMethod_value)
}
