// Code generated by protoc-gen-go from "memcache_service.proto"
// DO NOT EDIT!

package appengine

import proto "goprotobuf.googlecode.com/hg/proto"
import "math"
import "os"


// Reference proto, math & os imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf
var _ os.Error


type MemcacheServiceError_ErrorCode int32

const (
	MemcacheServiceError_OK                       = 0
	MemcacheServiceError_UNSPECIFIED_ERROR        = 1
	MemcacheServiceError_NAMESPACE_NOT_SET        = 2
	MemcacheServiceError_PERMISSION_DENIED        = 3
	MemcacheServiceError_NUM_BACKENDS_UNSPECIFIED = 4
)

var MemcacheServiceError_ErrorCode_name = map[int32]string{
	0: "OK",
	1: "UNSPECIFIED_ERROR",
	2: "NAMESPACE_NOT_SET",
	3: "PERMISSION_DENIED",
	4: "NUM_BACKENDS_UNSPECIFIED",
}
var MemcacheServiceError_ErrorCode_value = map[string]int32{
	"OK":                       0,
	"UNSPECIFIED_ERROR":        1,
	"NAMESPACE_NOT_SET":        2,
	"PERMISSION_DENIED":        3,
	"NUM_BACKENDS_UNSPECIFIED": 4,
}

func NewMemcacheServiceError_ErrorCode(x int32) *MemcacheServiceError_ErrorCode {
	e := MemcacheServiceError_ErrorCode(x)
	return &e
}
func (x MemcacheServiceError_ErrorCode) String() string {
	return proto.EnumName(MemcacheServiceError_ErrorCode_name, int32(x))
}

type MemcacheSetRequest_SetPolicy int32

const (
	MemcacheSetRequest_SET     = 1
	MemcacheSetRequest_ADD     = 2
	MemcacheSetRequest_REPLACE = 3
	MemcacheSetRequest_CAS     = 4
)

var MemcacheSetRequest_SetPolicy_name = map[int32]string{
	1: "SET",
	2: "ADD",
	3: "REPLACE",
	4: "CAS",
}
var MemcacheSetRequest_SetPolicy_value = map[string]int32{
	"SET":     1,
	"ADD":     2,
	"REPLACE": 3,
	"CAS":     4,
}

func NewMemcacheSetRequest_SetPolicy(x int32) *MemcacheSetRequest_SetPolicy {
	e := MemcacheSetRequest_SetPolicy(x)
	return &e
}
func (x MemcacheSetRequest_SetPolicy) String() string {
	return proto.EnumName(MemcacheSetRequest_SetPolicy_name, int32(x))
}

type MemcacheSetResponse_SetStatusCode int32

const (
	MemcacheSetResponse_STORED     = 1
	MemcacheSetResponse_NOT_STORED = 2
	MemcacheSetResponse_ERROR      = 3
	MemcacheSetResponse_EXISTS     = 4
)

var MemcacheSetResponse_SetStatusCode_name = map[int32]string{
	1: "STORED",
	2: "NOT_STORED",
	3: "ERROR",
	4: "EXISTS",
}
var MemcacheSetResponse_SetStatusCode_value = map[string]int32{
	"STORED":     1,
	"NOT_STORED": 2,
	"ERROR":      3,
	"EXISTS":     4,
}

func NewMemcacheSetResponse_SetStatusCode(x int32) *MemcacheSetResponse_SetStatusCode {
	e := MemcacheSetResponse_SetStatusCode(x)
	return &e
}
func (x MemcacheSetResponse_SetStatusCode) String() string {
	return proto.EnumName(MemcacheSetResponse_SetStatusCode_name, int32(x))
}

type MemcacheDeleteResponse_DeleteStatusCode int32

const (
	MemcacheDeleteResponse_DELETED   = 1
	MemcacheDeleteResponse_NOT_FOUND = 2
)

var MemcacheDeleteResponse_DeleteStatusCode_name = map[int32]string{
	1: "DELETED",
	2: "NOT_FOUND",
}
var MemcacheDeleteResponse_DeleteStatusCode_value = map[string]int32{
	"DELETED":   1,
	"NOT_FOUND": 2,
}

func NewMemcacheDeleteResponse_DeleteStatusCode(x int32) *MemcacheDeleteResponse_DeleteStatusCode {
	e := MemcacheDeleteResponse_DeleteStatusCode(x)
	return &e
}
func (x MemcacheDeleteResponse_DeleteStatusCode) String() string {
	return proto.EnumName(MemcacheDeleteResponse_DeleteStatusCode_name, int32(x))
}

type MemcacheIncrementRequest_Direction int32

const (
	MemcacheIncrementRequest_INCREMENT = 1
	MemcacheIncrementRequest_DECREMENT = 2
)

var MemcacheIncrementRequest_Direction_name = map[int32]string{
	1: "INCREMENT",
	2: "DECREMENT",
}
var MemcacheIncrementRequest_Direction_value = map[string]int32{
	"INCREMENT": 1,
	"DECREMENT": 2,
}

func NewMemcacheIncrementRequest_Direction(x int32) *MemcacheIncrementRequest_Direction {
	e := MemcacheIncrementRequest_Direction(x)
	return &e
}
func (x MemcacheIncrementRequest_Direction) String() string {
	return proto.EnumName(MemcacheIncrementRequest_Direction_name, int32(x))
}

type MemcacheIncrementResponse_IncrementStatusCode int32

const (
	MemcacheIncrementResponse_OK          = 1
	MemcacheIncrementResponse_NOT_CHANGED = 2
	MemcacheIncrementResponse_ERROR       = 3
)

var MemcacheIncrementResponse_IncrementStatusCode_name = map[int32]string{
	1: "OK",
	2: "NOT_CHANGED",
	3: "ERROR",
}
var MemcacheIncrementResponse_IncrementStatusCode_value = map[string]int32{
	"OK":          1,
	"NOT_CHANGED": 2,
	"ERROR":       3,
}

func NewMemcacheIncrementResponse_IncrementStatusCode(x int32) *MemcacheIncrementResponse_IncrementStatusCode {
	e := MemcacheIncrementResponse_IncrementStatusCode(x)
	return &e
}
func (x MemcacheIncrementResponse_IncrementStatusCode) String() string {
	return proto.EnumName(MemcacheIncrementResponse_IncrementStatusCode_name, int32(x))
}

type MemcacheServiceError struct {
	XXX_unrecognized []byte
}

func (this *MemcacheServiceError) Reset() {
	*this = MemcacheServiceError{}
}

type AppOverride struct {
	AppId                *string "PB(bytes,1,req,name=app_id)"
	NumMemcachegBackends *int32  "PB(varint,2,req,name=num_memcacheg_backends)"
	XXX_unrecognized     []byte
}

func (this *AppOverride) Reset() {
	*this = AppOverride{}
}

type MemcacheGetRequest struct {
	Key              [][]byte     "PB(bytes,1,rep,name=key)"
	NameSpace        *string      "PB(bytes,2,opt,name=name_space)"
	ForCas           *bool        "PB(varint,4,opt,name=for_cas)"
	Override         *AppOverride "PB(bytes,5,opt,name=override)"
	XXX_unrecognized []byte
}

func (this *MemcacheGetRequest) Reset() {
	*this = MemcacheGetRequest{}
}

type MemcacheGetResponse struct {
	Item             []*MemcacheGetResponse_Item "PB(group,1,rep,name=Item)"
	XXX_unrecognized []byte
}

func (this *MemcacheGetResponse) Reset() {
	*this = MemcacheGetResponse{}
}

type MemcacheGetResponse_Item struct {
	Key              []byte  "PB(bytes,2,req,name=key)"
	Value            []byte  "PB(bytes,3,req,name=value)"
	Flags            *uint32 "PB(fixed32,4,opt,name=flags)"
	CasId            *uint64 "PB(fixed64,5,opt,name=cas_id)"
	ExpiresInSeconds *int32  "PB(varint,6,opt,name=expires_in_seconds)"
	XXX_unrecognized []byte
}

func (this *MemcacheGetResponse_Item) Reset() {
	*this = MemcacheGetResponse_Item{}
}

type MemcacheSetRequest struct {
	Item             []*MemcacheSetRequest_Item "PB(group,1,rep,name=Item)"
	NameSpace        *string                    "PB(bytes,7,opt,name=name_space)"
	Override         *AppOverride               "PB(bytes,10,opt,name=override)"
	XXX_unrecognized []byte
}

func (this *MemcacheSetRequest) Reset() {
	*this = MemcacheSetRequest{}
}

type MemcacheSetRequest_Item struct {
	Key              []byte                        "PB(bytes,2,req,name=key)"
	Value            []byte                        "PB(bytes,3,req,name=value)"
	Flags            *uint32                       "PB(fixed32,4,opt,name=flags)"
	SetPolicy        *MemcacheSetRequest_SetPolicy "PB(varint,5,opt,name=set_policy,enum=appengine.MemcacheSetRequest_SetPolicy,def=1)"
	ExpirationTime   *uint32                       "PB(fixed32,6,opt,name=expiration_time,def=0)"
	CasId            *uint64                       "PB(fixed64,8,opt,name=cas_id)"
	ForCas           *bool                         "PB(varint,9,opt,name=for_cas)"
	XXX_unrecognized []byte
}

func (this *MemcacheSetRequest_Item) Reset() {
	*this = MemcacheSetRequest_Item{}
}

const Default_MemcacheSetRequest_Item_SetPolicy MemcacheSetRequest_SetPolicy = MemcacheSetRequest_SET
const Default_MemcacheSetRequest_Item_ExpirationTime uint32 = 0

type MemcacheSetResponse struct {
	SetStatus        []MemcacheSetResponse_SetStatusCode "PB(varint,1,rep,name=set_status,enum=appengine.MemcacheSetResponse_SetStatusCode)"
	XXX_unrecognized []byte
}

func (this *MemcacheSetResponse) Reset() {
	*this = MemcacheSetResponse{}
}

type MemcacheDeleteRequest struct {
	Item             []*MemcacheDeleteRequest_Item "PB(group,1,rep,name=Item)"
	NameSpace        *string                       "PB(bytes,4,opt,name=name_space)"
	Override         *AppOverride                  "PB(bytes,5,opt,name=override)"
	XXX_unrecognized []byte
}

func (this *MemcacheDeleteRequest) Reset() {
	*this = MemcacheDeleteRequest{}
}

type MemcacheDeleteRequest_Item struct {
	Key              []byte  "PB(bytes,2,req,name=key)"
	DeleteTime       *uint32 "PB(fixed32,3,opt,name=delete_time,def=0)"
	XXX_unrecognized []byte
}

func (this *MemcacheDeleteRequest_Item) Reset() {
	*this = MemcacheDeleteRequest_Item{}
}

const Default_MemcacheDeleteRequest_Item_DeleteTime uint32 = 0

type MemcacheDeleteResponse struct {
	DeleteStatus     []MemcacheDeleteResponse_DeleteStatusCode "PB(varint,1,rep,name=delete_status,enum=appengine.MemcacheDeleteResponse_DeleteStatusCode)"
	XXX_unrecognized []byte
}

func (this *MemcacheDeleteResponse) Reset() {
	*this = MemcacheDeleteResponse{}
}

type MemcacheIncrementRequest struct {
	Key              []byte                              "PB(bytes,1,req,name=key)"
	NameSpace        *string                             "PB(bytes,4,opt,name=name_space)"
	Delta            *uint64                             "PB(varint,2,opt,name=delta,def=1)"
	Direction        *MemcacheIncrementRequest_Direction "PB(varint,3,opt,name=direction,enum=appengine.MemcacheIncrementRequest_Direction,def=1)"
	InitialValue     *uint64                             "PB(varint,5,opt,name=initial_value)"
	InitialFlags     *uint32                             "PB(fixed32,6,opt,name=initial_flags)"
	Override         *AppOverride                        "PB(bytes,7,opt,name=override)"
	XXX_unrecognized []byte
}

func (this *MemcacheIncrementRequest) Reset() {
	*this = MemcacheIncrementRequest{}
}

const Default_MemcacheIncrementRequest_Delta uint64 = 1
const Default_MemcacheIncrementRequest_Direction MemcacheIncrementRequest_Direction = MemcacheIncrementRequest_INCREMENT

type MemcacheIncrementResponse struct {
	NewValue         *uint64                                        "PB(varint,1,opt,name=new_value)"
	IncrementStatus  *MemcacheIncrementResponse_IncrementStatusCode "PB(varint,2,opt,name=increment_status,enum=appengine.MemcacheIncrementResponse_IncrementStatusCode)"
	XXX_unrecognized []byte
}

func (this *MemcacheIncrementResponse) Reset() {
	*this = MemcacheIncrementResponse{}
}

type MemcacheBatchIncrementRequest struct {
	NameSpace        *string                     "PB(bytes,1,opt,name=name_space)"
	Item             []*MemcacheIncrementRequest "PB(bytes,2,rep,name=item)"
	Override         *AppOverride                "PB(bytes,3,opt,name=override)"
	XXX_unrecognized []byte
}

func (this *MemcacheBatchIncrementRequest) Reset() {
	*this = MemcacheBatchIncrementRequest{}
}

type MemcacheBatchIncrementResponse struct {
	Item             []*MemcacheIncrementResponse "PB(bytes,1,rep,name=item)"
	XXX_unrecognized []byte
}

func (this *MemcacheBatchIncrementResponse) Reset() {
	*this = MemcacheBatchIncrementResponse{}
}

type MemcacheFlushRequest struct {
	Override         *AppOverride "PB(bytes,1,opt,name=override)"
	XXX_unrecognized []byte
}

func (this *MemcacheFlushRequest) Reset() {
	*this = MemcacheFlushRequest{}
}

type MemcacheFlushResponse struct {
	XXX_unrecognized []byte
}

func (this *MemcacheFlushResponse) Reset() {
	*this = MemcacheFlushResponse{}
}

type MemcacheStatsRequest struct {
	Override         *AppOverride "PB(bytes,1,opt,name=override)"
	XXX_unrecognized []byte
}

func (this *MemcacheStatsRequest) Reset() {
	*this = MemcacheStatsRequest{}
}

type MergedNamespaceStats struct {
	Hits             *uint64 "PB(varint,1,req,name=hits)"
	Misses           *uint64 "PB(varint,2,req,name=misses)"
	ByteHits         *uint64 "PB(varint,3,req,name=byte_hits)"
	Items            *uint64 "PB(varint,4,req,name=items)"
	Bytes            *uint64 "PB(varint,5,req,name=bytes)"
	OldestItemAge    *uint32 "PB(fixed32,6,req,name=oldest_item_age)"
	XXX_unrecognized []byte
}

func (this *MergedNamespaceStats) Reset() {
	*this = MergedNamespaceStats{}
}

type MemcacheStatsResponse struct {
	Stats            *MergedNamespaceStats "PB(bytes,1,opt,name=stats)"
	XXX_unrecognized []byte
}

func (this *MemcacheStatsResponse) Reset() {
	*this = MemcacheStatsResponse{}
}

type MemcacheGrabTailRequest struct {
	ItemCount        *int32       "PB(varint,1,req,name=item_count)"
	NameSpace        *string      "PB(bytes,2,opt,name=name_space)"
	Override         *AppOverride "PB(bytes,3,opt,name=override)"
	XXX_unrecognized []byte
}

func (this *MemcacheGrabTailRequest) Reset() {
	*this = MemcacheGrabTailRequest{}
}

type MemcacheGrabTailResponse struct {
	Item             []*MemcacheGrabTailResponse_Item "PB(group,1,rep,name=Item)"
	XXX_unrecognized []byte
}

func (this *MemcacheGrabTailResponse) Reset() {
	*this = MemcacheGrabTailResponse{}
}

type MemcacheGrabTailResponse_Item struct {
	Value            []byte  "PB(bytes,2,req,name=value)"
	Flags            *uint32 "PB(fixed32,3,opt,name=flags)"
	XXX_unrecognized []byte
}

func (this *MemcacheGrabTailResponse_Item) Reset() {
	*this = MemcacheGrabTailResponse_Item{}
}

func init() {
	proto.RegisterEnum("appengine.MemcacheServiceError_ErrorCode", MemcacheServiceError_ErrorCode_name, MemcacheServiceError_ErrorCode_value)
	proto.RegisterEnum("appengine.MemcacheSetRequest_SetPolicy", MemcacheSetRequest_SetPolicy_name, MemcacheSetRequest_SetPolicy_value)
	proto.RegisterEnum("appengine.MemcacheSetResponse_SetStatusCode", MemcacheSetResponse_SetStatusCode_name, MemcacheSetResponse_SetStatusCode_value)
	proto.RegisterEnum("appengine.MemcacheDeleteResponse_DeleteStatusCode", MemcacheDeleteResponse_DeleteStatusCode_name, MemcacheDeleteResponse_DeleteStatusCode_value)
	proto.RegisterEnum("appengine.MemcacheIncrementRequest_Direction", MemcacheIncrementRequest_Direction_name, MemcacheIncrementRequest_Direction_value)
	proto.RegisterEnum("appengine.MemcacheIncrementResponse_IncrementStatusCode", MemcacheIncrementResponse_IncrementStatusCode_name, MemcacheIncrementResponse_IncrementStatusCode_value)
}
