// Code generated by protoc-gen-go from "remote_api.proto"
// DO NOT EDIT!

package remote_api

import proto "goprotobuf.googlecode.com/hg/proto"
import "math"
import "os"


// Reference proto, math & os imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf
var _ os.Error


type Request struct {
	ServiceName      *string "PB(bytes,2,req,name=service_name)"
	Method           *string "PB(bytes,3,req,name=method)"
	Request          []byte  "PB(bytes,4,req,name=request)"
	XXX_unrecognized []byte
}

func (this *Request) Reset() {
	*this = Request{}
}

type ApplicationError struct {
	Code             *int32  "PB(varint,1,req,name=code)"
	Detail           *string "PB(bytes,2,req,name=detail)"
	XXX_unrecognized []byte
}

func (this *ApplicationError) Reset() {
	*this = ApplicationError{}
}

type Response struct {
	Response         []byte            "PB(bytes,1,opt,name=response)"
	Exception        []byte            "PB(bytes,2,opt,name=exception)"
	ApplicationError *ApplicationError "PB(bytes,3,opt,name=application_error)"
	JavaException    []byte            "PB(bytes,4,opt,name=java_exception)"
	XXX_unrecognized []byte
}

func (this *Response) Reset() {
	*this = Response{}
}

func init() {
}
